In [1]:
from pathlib import Path

while Path.cwd().name != 'ambignli':
    %cd ..

/mmfs1/gscratch/xlab/alisaliu/ambignli

In [2]:
import pandas as pd

In [9]:
splits = ['train', 'dev', 'test']
for split in splits:
    df = pd.read_csv(f'data/unli/raw/{split}.csv')
    df = df.rename({'pre': 'premise', 'hyp': 'hypothesis', 'unli': 'gold'}, axis=1).drop('nli', axis=1)
    df.to_json(f'data/unli/{split}.jsonl', lines=True, orient='records')

In [11]:
snli_train = pd.read_json('data/snli/train.jsonl', lines=True)
def surrogate_function(y):
    """
    surrogate function T → [0, 1] that maps SNLI categorical labels {ENT, NEU, CON} 
    to the average score of all u-SNLI training annotations labeled with t in SNLI
    
    s: {ENT → 0.9272; NEU → 0.4250; CON → 0.0209}
    """
snli_train.apply()

,id,gold,pairID,premise,hypothesis,genre
0,0,neutral,3416050480.jpg#4r1n,A person on a horse jumps over a broken down a...,A person is training his horse for a competition.,snli
1,1,contradiction,3416050480.jpg#4r1c,A person on a horse jumps over a broken down a...,"A person is at a diner, ordering an omelette.",snli
2,2,entailment,3416050480.jpg#4r1e,A person on a horse jumps over a broken down a...,"A person is outdoors, on a horse.",snli
3,3,neutral,2267923837.jpg#2r1n,Children smiling and waving at camera,They are smiling at their parents,snli
4,4,entailment,2267923837.jpg#2r1e,Children smiling and waving at camera,There are children present,snli
...,...,...,...,...,...,...
550147,550147,contradiction,2267923837.jpg#3r1c,Four dirty and barefooted children.,four kids won awards for 'cleanest feet',snli
550148,550148,neutral,2267923837.jpg#3r1n,Four dirty and barefooted children.,"four homeless children had their shoes stolen,...",snli
550149,550149,neutral,7979219683.jpg#2r1n,A man is surfing in a bodysuit in beautiful bl...,A man in a bodysuit is competing in a surfing ...,snli
550150,550150,contradiction,7979219683.jpg#2r1c,A man is surfing in a bodysuit in beautiful bl...,A man in a business suit is heading to a board...,snli
550151,550151,entailment,7979219683.jpg#2r1e,A man is surfing in a bodysuit in beautiful bl...,On the beautiful blue water there is a man in ...,snli